<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], []],
    'place-orders' => [[], ['_controller' => 'App\\Controller\\OrdersController::placeAction'], [], [['text', '/orders']], [], []],
    'take-orders' => [['id'], ['id' => null, '_controller' => 'App\\Controller\\OrdersController::takeAction'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/orders']], [], []],
    'list-orders' => [['page', 'limit'], ['page' => null, 'limit' => null, '_controller' => 'App\\Controller\\OrdersController::listAction'], [], [['variable', '/', '[^/]++', 'limit', true], ['variable', '/', '[^/]++', 'page', true], ['text', '/orders/list']], [], []],
];
