<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTNJxCwk\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTNJxCwk/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerTNJxCwk.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerTNJxCwk\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerTNJxCwk\App_KernelProdContainer([
    'container.build_hash' => 'TNJxCwk',
    'container.build_id' => 'e3ac90c9',
    'container.build_time' => 1590434832,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTNJxCwk');
